### ISSUE TITLE
Case "Row" Component

### ISSUE THREAD

**Issue by CharlesDLandau** [codefordc/rfj_expungement#20]
**Motivation:**
Each client has a case and each case may have more than one charge against the client. The top level data about each charge will be represented in a "Row" of the top level data view. The row displays data like the name of the charge, whether it's a felony or a misdemenor. The user clicks some part of this row to navigate to the case eligibility evaluation workflow.

_Note: The implementation does not need to use `tr`, it could just as easily be a card or whatever._

**Accepts:**
`to`: destination component(s)
Data fields: The top level component renders each case based on user input, so any data fields such as name of the charge

**Renders:**
Data fields
Indicator component

**Pushes to context:**
??

**Consumes from context:**
??

**Comment by beckybell13** [comment]
(working on this)

**Comment by CharlesDLandau** [comment]
This is built out
