### ISSUE TITLE
Outcome Indicator Component

### ISSUE THREAD

**Issue by CharlesDLandau** [codefordc/rfj_expungement#21]
**Motivation:**
Each client has a case and each case may have more than one charge against the client. The top level data about each charge will be represented in a "Row" of the top level data view. The row displays data like the name of the charge, whether it's a felony or a misdemeanor, but it should also have an "Indicator" which shows at-a-glance what the status of the row is.

**Accepts:**
`chargeId` (or some identifier): used to match on the specific charge that the indicator should listen to in the Context.

**Renders:**
An indicator, such as a circle which changes color and hovertext based on the outcome of evaluations. For example if context indicates that the charge has not been evaluated, show as grey, or if ineligible show as red.

**Pushes to context:**
???

**Consumes from context:**
State/outcome of the charge.

**Comment by dylanbyars** [comment]
I'll take this one.
