### ISSUE TITLE
Save to file feature

### ISSUE THREAD

**Issue by CharlesDLandau** [codefordc/rfj_expungement#22]
Before delivering this project it may become necessary to implement a "save to file" feature, probably save-to-pdf. Ideally, we'll use the print to pdf APIs. At time of writing #15 needs to be finished before this issue can be specced out.

**Comment by Fran33** [comment]
pull request submitted for this.

**Comment by CharlesDLandau** [comment]
There's still a little more tracking to this but we'll move to the PR
