### ISSUE TITLE
Charge eligibility view

### ISSUE THREAD

**Issue by CharlesDLandau** [codefordc/rfj_expungement#24]
**Motivation:**
Once the user navigates "in" to a specific charge that is part of the case, they should be presented with a sequence of questions which map to the data model in the Context object.

Accepts:
Passthrough props from #19 (?)

Renders:
Form components as in #23
Annotations consumed from context

Pushes to context:
User input from the web form

Consumes from context:
Web form annotations, field types, data model generally

**Comment by trevor-jameson** [comment]
working through this

**Comment by CharlesDLandau** [comment]
Implemented, but needs cleaning (will happen in a new issue)
