### ISSUE TITLE
Persistent nav buttons

### ISSUE THREAD

**Issue by CharlesDLandau** [codefordc/rfj_expungement#25]
In a nav bar or prominent location in the root view, buttons should exist with basic nav functions including:

1. Back to root view (e.g. the top level data view in #19 )
2. Reset project (needs confirmation modal)
3. Save to <something> dummy button (may need a modal)

_Note: an actual save feature is out of scope for this issue. See #22_

**Comment by dhruvturakhia** [comment]
Picking this up :)

**Comment by CharlesDLandau** [comment]
This is implemented
