### ISSUE TITLE
Rich Text Editor

### ISSUE THREAD

**Issue by CharlesDLandau** [codefordc/rfj_expungement#26]
The Rich Text Editor feature for this project is intended to be a space for freeform notes. The RTE should be approachable but does not need to be a fully-featured word processing UX.

At this time I am writing the draft schema for the data model with the assumption that the RTE values will be encoded at the root of the data model. That is, there will be no granularity about where notes are assigned.

**Comment by CyberD123** [comment]
AJ (oe5jey on Slack) and I (Debbie Berlin) have been following this tutorial: https://draftjs.org/ which uses a library to help create a Rich Text Editor. We were able to insert a very basic editor (that allows free form typing only). The tutorial advises including a Draft.css file to allow for buttons, etc. for text editing which we were not yet sure how to include. AJ will create a separate branch with the code. Help appreciated -- thank you. This is the link for AJ's branch: https://github.com/xee5ch/rfj_expungement/tree/issue-26-spike-rich-text-editor

**Comment by CyberD123** [comment]
This issue is also being worked on in: Rich Text Editor Draft #60 pull request.

**Comment by froi** [comment]
Hi @CharlesDLandau hope all is well 😄 

The PR reference has been merged ( #60 ). Should we close this issue and complete the items found in #15?
