### ISSUE TITLE
Using Bit for Component Management and Documentation

### ISSUE THREAD

**Issue by VictoriaGuido** [codefordc/rfj_expungement#35]
Bit is an extension of Git, destructing repositories into discrete components and supports their lifecycle. Bit will automatically detect and manage all the components in a project, their dependencies, and documentation. Bit supports documentation in both markdown and JSDOS.

It lets you independently build, test, version, update and publish components in true isolation from the rest of the repository. 

Follow directions in the bit quick start https://docs.bit.dev/docs/quick-start

**Comment by CharlesDLandau** [comment]
I think we should still try to do this but aware of our bandwidth right now I'm going to say let's push right.

Closing as stale
