### ISSUE TITLE
CI?

### ISSUE THREAD

**Issue by CharlesDLandau** [codefordc/rfj_expungement#4]
Travis? Circle? any preferences get logged here.

**Comment by froi** [comment]
I think Travis is the easier path and the one that most devs will be familiar with. That said I prefer to use Circle CI.

Circle CI let us configure more than just unit and integration tests. We can also interface with other services if we wanted to.

Another thing to consider is that by November GitHub Actions will be out of beta and we could use that for better integration with GitHub itself.

**Comment by CharlesDLandau** [comment]
@mkalish reports that Circle is set up
