### ISSUE TITLE
Open up the wiki

### ISSUE THREAD

**Issue by NickSto** [codefordc/rfj_expungement#49]
Hey, so it turns out you can't submit a pull request to the wiki.

The repo owner themselves have to enable the wiki.

FYI, I created a page with a few of my notes [here](https://github.com/NickSto/rfj_expungement/wiki/Getting-up-to-speed). I guess once it's enabled in this repo I'll copy it over manually?

**Comment by CharlesDLandau** [comment]
Should be available now, but wiki contributions need to come thru git flow I think
