### ISSUE TITLE
Input text fields are slow

### ISSUE THREAD

**Issue by JimmyJay1985** [codefordc/rfj_expungement#59]
Seems like there is a delay if you're entering in a lot of characters.

Possible issues:

1) Updating after every keystroke is potentially too slow.
2) Potentially, a lot of the DOM is re-rendered when characters are entered. We can test this with logging statements or the react debugger from within chrome.

**Comment by CharlesDLandau** [comment]
This is the result of:
https://github.com/codefordc/rfj_expungement/blob/c62389fe8f293c5d724b3fa061a0b7add51e61cf/contexts/casecontroller.js#L72-L77

**Comment by JimmyJay1985** [comment]
Added changes for Eval Name to suppress state update for one second. Hopefully this can be used elsewhere in the application to improve performance.

**Comment by CharlesDLandau** [comment]
Closed by #62 and #69
