### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by CharlesDLandau** [codefordc/rfj_expungement#6]
TODO:

- [x] Meaningful README.md
- [x] CONTRIBUTING.md
- [x] LICENSE.md
- [ ]  Storybook?
- [ ] Issue template?
- [ ] ???

**Comment by froi** [comment]
Hey @CharlesDLandau I hope you don't mind we editing the content of the issue. I've just changed the number list to one with checkboxes.

**Comment by CharlesDLandau** [comment]
No problem editing. If you think the community insights page is a better tracker for these items, then I can close this.

**Comment by froi** [comment]
Nope. It's good to have this here. Let us have a history of when these things are being done.

**Comment by froi** [comment]
Marked the README as done since it was merged.

**Comment by CharlesDLandau** [comment]
Closing as stale
