### ISSUE TITLE
DOB (Date of Birth) Date Picker input section

### ISSUE THREAD

**Issue by CyberD123** [codefordc/rfj_expungement#63]
DOB (Date of Birth) picker has a red error on onset because it’s trying to display a DOB value that hasn't been set, perhaps could have it display MM/DD/YYYY

(DOB & case term dates are defined in ClientInfoTable.js)

**Comment by Fran33** [comment]
I cannot reproduce this error. The "initialDate" of the ComposedDatePicker can be set to a date "2018-04-05" or "new Date()" or left null, in which case it defaults to the current system date.
So this issue might be OBE.

**Comment by froi** [comment]
This shows up when running the project in the Next.js dev server.

![image](https://user-images.githubusercontent.com/1918027/74689811-8cfe7d00-51aa-11ea-800f-59127bc0419a.png)

**Comment by cmazzullo** [comment]
This is resolved on master.

> This shows up when running the project in the Next.js dev server.
> 
> ![image](https://user-images.githubusercontent.com/1918027/74689811-8cfe7d00-51aa-11ea-800f-59127bc0419a.png)

The next.js server is running old code, unless someone has updated it recently.

**Comment by cmazzullo** [comment]
This issue should be closed @CharlesDLandau
