### ISSUE TITLE
PERSIST CASEDATA button

### ISSUE THREAD

**Issue by CyberD123** [codefordc/rfj_expungement#66]
PERSIST CASEDATA button defined in ClientInfoTable.js should be made to look like a button, right now looks like an error msg, suggestion: put oval shading around it to resemble a button

**Comment by wjpurdum** [comment]
Looks like there is shading there on hover - was this the intended fix?

**Comment by xee5ch** [comment]
I see we merged my PR, can we close this now, @wjpurdum and @CharlesDLandau? I did not think my solution was ideal, so let me know if that quick fix is sufficient.

**Comment by froi** [comment]
Closing this as it seem to be solved.

![image](https://user-images.githubusercontent.com/1918027/74689910-fc746c80-51aa-11ea-99f0-bb566393f20b.png)

Please reopen if this is not the case.
