### ISSUE TITLE
datamodel.json may be obsolete

### ISSUE THREAD

**Issue by CyberD123** [codefordc/rfj_expungement#67]
casecontainer.json & datamodel.json seem to have duplicate info, output reads from casecontainer.json, datamodel.json may be obsolete

**Comment by Fran33** [comment]
I agree datamodel.json is not used, but it represents a fuller data example that casecontainer.json, so casecontainer should be expanded to initialize, as much data as datamodel.json does, to an example data before deleting datamodel.json. e.g. add charges to casecontainer.json

**Comment by cmazzullo** [comment]
Looking into this

**Comment by cmazzullo** [comment]
This was resolved in #77 and can be closed

**Comment by froi** [comment]
Closing issue as it was addressed in #77
