### ISSUE TITLE
Repo Description

### ISSUE THREAD

**Issue by froi** [codefordc/rfj_expungement#7]
I wanted to start a conversation about the description of our project. This is the short description found under the repo title. This is not the text for the README.md. 

This is a first stab at it, if you agree with it just give a thumbs up to this initial comment. Anything else comment down below 😄 

__Description__

Tool for pro bono attorneys helping the Rising for Justice’s Expungement Clinic.

Any thoughts?

**Comment by froi** [comment]
Taking the two 👍 as agreement and setting the description.

**Comment by froi** [comment]
Cancel that. We need admin privileges for that. I think that's our next step.

**Comment by CharlesDLandau** [comment]
Paging @mkalish -- we apparently need an organization owner to affix the description at the top of this issue?

**Comment by CharlesDLandau** [comment]
I am a repo maintainer and have made the edits
