### ISSUE TITLE
Requesting collaborator status (ability to write to the repo)

### ISSUE THREAD

**Issue by cmazzullo** [codefordc/rfj_expungement#93]
Hey Charles and Froi,

Hope you're both safe and doing well!

I just wanted to request collaborator status on this repo, so I can help review and merge some of the extant pull requests, and new ones as they come up. This would also help me make contributions - there are some parts of the extant pull requests I'd like to use, and can't until they're merged into master.

Of course if you'd prefer to keep control of the repo in fewer hands I completely understand.

Best,
Chris

**Comment by CharlesDLandau** [comment]
I don't seem to be able to do that. Let's slack Michael Kalish
